language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

matrix:
  fast_finish: true
  allow_failures:
    # hhvm does not understand JMS' object inheritance during (de)serialization
    - php: hhvm

before_script: composer install

script: ./bin/phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
