CL\Slack\Model\Channel:
    properties:
        id:
            type: string
        name:
            type: string
        latest:
            type: CL\Slack\Model\SimpleMessage
        lastRead:
            type: float
        isMember:
            type: boolean
        members:
            type: array<string>
        topic:
            type: CL\Slack\Model\Customizable
        purpose:
            type: CL\Slack\Model\Customizable
